---
kind: Template
apiVersion: v1
metadata:
  name: ubuntu
  annotations:
    openshift.io/display-name: Ubuntu
    description: |-
      Ubuntu is a Debian-based Linux operating system. Xenial Xerus is the Ubuntu codename for version 16.04 LTS of the Ubuntu Linux-based operating system., see http://www.ubuntu.com/server.

      WARNING: Any data stored will be lost upon pod destruction.
    iconClass: icon-machine
    tags: torpeto,ubuntu
    template.openshift.io/long-description: This template provides a standalone OpenNebula
      master server with a database created.  The database is not stored on persistent storage,
      so any restart of the service will result in all data being lost.
    template.openshift.io/provider-display-name: Megam Systems.
    template.openshift.io/documentation-url: https://docs.megam.io
    template.openshift.io/support-url: https://github.com/megamsys/support
message: |-
  The following service(s) have been created in your project: ${ONE_SERVICE_NAME}.

         Username: ${ONE_USER}
         Password:
   Connection URL: http://${ONE_SERVICE_NAME}:9869/

  For more information about using this template, including OpenShift considerations, see https://github.com/megamsys/kubeshift.
labels:
  template: ubuntu
  tosca_type: vertice.torpedo 
objects:
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-vm
  annotations:
    kubernetes.io/target-runtime: virtlet
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: ubuntu-vm
    image: virtlet/cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
  volumes:
  - name: test
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: nocloud
        metadata: |
          instance-id: ubuntu-vm-001
          local-hostname: ubuntu-vm
        userdata: |
          #cloud-config
          users:
          - name: root
            ssh-authorized-keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCaJEcFDXEK2ZbX0ZLS1EIYFZRbDAcRfuVjpstSc0De8+sV1aiu+dePxdkuDRwqFtCyk6dEZkssjOkBXtri00MECLkir6FcH3kKOJtbJ6vy3uaJc9w1ERo+wyl6SkAh/+JTJkp7QRXj8oylW5E20LsbnA/dIwWzAF51PPwF7A7FtNg9DnwPqMkxFo1Th/buOMKbP5ZA1mmNNtmzbMpMfJATvVyiv3ccsSJKOiyQr6UG+j7sc/7jMVz5Xk34Vd0l8GwcB0334MchHckmqDB142h/NCWTr8oLakDNvkfC1YneAfAO41hDkUbxPtVBG5M/o7P4fxoqiHEX+ZLfRxDtHB53 me@localhost
          ssh_pwauth: True

parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
  required: true
- name: VERSION
  displayName: Version of Ubuntu
  description: Version of Ubuntu image to be used (16.04 or 14.04).
  value: '16.04'
  required: true

